- name: github secrets
  hosts: "{{ target_ip }}"
  vars:
    # Change these variables to be what you want.
    local_user: "username"
    git_repo: "USER/REPO"
    # These are the secrets to be encrypted. Referenced on lines 55/56 and 76/77
    # Make sure to update the names and add any variables you add here on those lines.
    secret_1: "shh"
    secret_2: "meow"
  become: true
  tasks:
    - name: Generate an OpenSSH keypair with a different algorithm (dsa)
      become_user: "{{ local_user }}"
      community.crypto.openssh_keypair:
        path: "/tmp/id_{{ username }}"
        type: ed25519
      delegate_to: localhost

    - name: Copy authorized_keys for user
      authorized_key:
        user: "{{ username }}"
        state: present
        key: "{{ lookup('file', '/tmp/id_{{ username }}.pub') }}"
        exclusive: true

    # Get repo public key
    - name: Get {{ git_repo }} public key.
      become_user: "{{ local_user }}"
      shell:
        cmd: |
          gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-Github-Api-Version: 2022-11-28" \
            /repos/{{ git_repo }}/actions/secrets/public-key
      delegate_to: localhost
      register: key

    - name: Extract key and key_id values
      set_fact:
        repo_pub_key: "{{ key.stdout | from_json | json_query('key') }}"
        repo_key_id: "{{ key.stdout | from_json | json_query('key_id') }}"

    - name: Encrypt the secrets
      become_user: "{{ local_user }}"
      shell:
        cmd: |
          node /path/to/gh_secret.js "{{ item }}" "{{ repo_pub_key }}"
      delegate_to: localhost
      no_log: true
      register: secrets
      loop:
        # These are the secrets passed in via -e command.
        - "{{ secret_1 }}"
        - "{{ secret_2 }}"

    - name: Loop through the registered variable and set facts
      no_log: true
      set_fact:
        "{{ item.0 }}": "{{ item.1.stdout }}"
      with_together:
        # These are the names of the secrets on GitHub
        - - secret_one
          - secret_two
        - "{{ secrets.results }}"

    # Note: Requires being logged into the gh api CLI on the host machine
    - name: Add secrets to GH.
      become_user: "{{ local_user }}"
      no_log: true
      shell:
        cmd: |
          gh api --method PUT -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/{{ git_repo }}/actions/secrets/{{ item.0 | upper }} -f encrypted_value='{{ item.1 }}' -f key_id='{{ repo_key_id }}'
      with_together:
        - - secret_1
          - secret_2
        - - "{{ secret_1 }}"
          - "{{ secret_2 }}"
      delegate_to: localhost
